from pbsparser import PBSParser

PATH_TO_FILE = "pokemon.txt"

# parses the dictionary passed in and spits it out as a C struct
class PBSPokemon:
    name: str = ""
    types: list[str] = []
    base_stats: list[int] = []
    level_up: list[any] = []
    base_xp: int = 100
    catch_rate: int = 255

    def __init__(self, pokemon_data):
        self.name = pokemon_data["Name"]
        self.types = list(map(lambda x: f"TYPE_{x.upper()}", pokemon_data["Types"].split(",")))
        if len(self.types) == 1:
            self.types.append("TYPE_NULL")
        self.base_stats = pokemon_data["BaseStats"].split(",")
        self.level_up = pokemon_data["Moves"].split(",")
        self.base_xp = int(pokemon_data["BaseExp"])
        self.catch_rate = int(pokemon_data["CatchRate"])

    def _level_ups(self) -> str:
        _moves: str = "{\n"
        for idx in range(0, len(self.level_up), 2):
            _moves += f"\t\t\t{{ .move = {self.level_up[idx+1]}, .level = {self.level_up[idx]} }},\n"
        _moves += "\t\t}"
        return _moves


    def to_string(self) -> str:
        return \
f"""{{
        .name = "{self.name}",
        .types = {{{self.types[0]}, {self.types[1]}}},
        .base = PKMN_STATS({self.base_stats[0]}, {self.base_stats[1]}, {self.base_stats[2]}, {self.base_stats[3]}, {self.base_stats[4]}, {self.base_stats[5]}),
        .base_xp = {self.base_xp},
        .catch_rate = {self.catch_rate},
        .level_up_moves = {self._level_ups()},
    }}"""


parsed = PBSParser(PATH_TO_FILE).parse()
_species_count = len(parsed.keys())

# Start building the header file.
_file_contents = \
f"""
#define SPECIES_COUNT {_species_count}
const static pkmn_species_t PokemonSpecies[SPECIES_COUNT] = {{
"""

# Iterate through all the pokemon
for idx, pokemon_name in enumerate(parsed.keys()):
    _pkmn = PBSPokemon(parsed[pokemon_name])
    _file_contents += f"\t[{idx}] = {_pkmn.to_string()},\n"
    
_file_contents += "\n};\n\n"

# Create macros for each pokemon
for idx, pkmn_name in enumerate(parsed.keys()):
    _file_contents += f"#define {pkmn_name} (&PokemonSpecies[{idx}])\n"


_whole_file = f"""
#ifndef _PKMN_POKEMON_DATA_H
#define _PKMN_POKEMON_DATA_H
#include "../pkmn_species.h"
#include "pkmn_move_data.h"
/*
    THIS FILE IS GENERATED BY THE 'scripts/parse_pokemon.py' SCRIPT!
    DO NOT MAKE MEANINGFUL CHANGES INTO THIS FILE!
*/

{_file_contents}
#endif
"""

# Write to file
file = open("../include/data/pkmn_pokemon_data.h", "w")
file.write(_whole_file)
file.close()
