#ifndef PKMN_TYPE_H
#define PKMN_TYPE_H

#define TYPE_MAX_IMMUNITIES  2
#define TYPE_MAX_RESISTANCES 4
#define TYPE_MAX_WEAKNESSES  4

typedef enum pkmn_type_t {
	TYPE_NULL = 0,
	TYPE_NORMAL,
	TYPE_FIGHTING,
	TYPE_FLYING,
	TYPE_POISON,
	TYPE_GROUND,
	TYPE_ROCK,
	TYPE_BUG,
	TYPE_GHOST,
	TYPE_STEEL,
	TYPE_FIRE,
	TYPE_WATER,
	TYPE_GRASS,
	TYPE_ELECTRIC,
	TYPE_PSYCHIC,
	TYPE_ICE,
	TYPE_DRAGON,
	TYPE_DARK,
	TYPE_FAIRY,
    TYPE_COUNT,
} pkmn_type_t ;

static const char* pkmn_type_to_str(pkmn_type_t type) {
	static const char* sTypesStr[] = {
		[TYPE_NULL] = "TYPE_NULL",
		[TYPE_NORMAL] = "TYPE_NORMAL",
		[TYPE_FIGHTING] = "TYPE_FIGHTING",
		[TYPE_FLYING] = "TYPE_FLYING",
		[TYPE_POISON] = "TYPE_POISON",
		[TYPE_GROUND] = "TYPE_GROUND",
		[TYPE_ROCK] = "TYPE_ROCK",
		[TYPE_BUG] = "TYPE_BUG",
		[TYPE_GHOST] = "TYPE_GHOST",
		[TYPE_STEEL] = "TYPE_STEEL",
		[TYPE_FIRE] = "TYPE_FIRE",
		[TYPE_WATER] = "TYPE_WATER",
		[TYPE_GRASS] = "TYPE_GRASS",
		[TYPE_ELECTRIC] = "TYPE_ELECTRIC",
		[TYPE_PSYCHIC] = "TYPE_PSYCHIC",
		[TYPE_ICE] = "TYPE_ICE",
		[TYPE_DRAGON] = "TYPE_DRAGON",
		[TYPE_DARK] = "TYPE_DARK",
		[TYPE_FAIRY] = "TYPE_FAIRY",
		[TYPE_COUNT] = "TYPE_COUNT",
	};
	return sTypesStr[type];
}

/*
const static pkmn_type_t s_Weaknesses[TYPE_COUNT][TYPE_MAX_WEAKNESSES] = {
    [TYPE_NULL] = {},
    [TYPE_FIRE] = {

    }
};
*/

#endif
